### ISSUE TITLE
Stardew Access doesn't read the chat on Stardew Valley for Mac

### ISSUE THREAD

**Issue by fz0308** [stardew-access/stardew-access#326] opened 2024-04-18 10:23 UTC
Stardew Access doesn't read the chat on Stardew Valley for mac. Whatever I type on chat, the mods keeps silent and also doesn't read the reply.

**Comment by khanshoaib3** [comment] 2024-05-23 16:02
Closing this as this is a duplicate of #325

**Closed as not planned by khanshoaib3** 2024-05-23 16:02 UTC
